version: '3'  # version of compose format

services:
  taco-service:
    build: flaskr  # path is relative to docker-compose.yml location
    volumes:
      - ./flaskr:/usr/src/flaskr # mount point
    ports:
      - 5001:80  # host:container

  website:
    image: php:apache  # pulling image from DockerHub
    volumes:
      - ./website:/var/www/html # mount
    ports:
      - 5000:80  # host:container
    depends_on:
      - taco-service  # website is not going to work
                             # unless observatory-service is running